# https://wandb.ai

wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  # wandb project to log to
  project: "GFS_TEST_RUN"
  name: "${model_name}"
  # location to store the wandb local logs
  save_dir: "GFS_TEST_RUN"
  offline: False # set True to store all logs only locally
  # id: null # pass correct id to resume experiment!
  id: "${oc.env:WANDB_RUN_ID}"
  # entity: ""  # set to name of your wandb team or just remove it
  log_model: True
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
