name: dwd-icon-eu
platform: huggingface
dataset_name: pvnet/dwd-icon-eu

grid:
  height: 561
  width: 1097
  latitude_bounds: [65.0, 30.0]  # [max, min] for descending order
  longitude_bounds: [-23.5, 45.0]  # [min, max]

variables:
  - t_2m
  - t_g
  - aswdifd_s
  - aswdir_s
  - relhum_2m
  - td_2m
  - u_10m
  - v_10m
  - vmax_10m
  - pmsl
  - clct
  - clcl
  - clcm
  - clch
  - ww
  - z0
  - h_snow
  - w_snow
  - tot_prec
  - runoff_g
  - runoff_s
  - cape_con
  - alb_rad
