_target_: pvnet.models.multimodal.multimodal.Model

output_quantiles: [0.02, 0.1, 0.25, 0.5, 0.75, 0.9, 0.98]

#--------------------------------------------
# NWP encoder
#--------------------------------------------

nwp_encoders_dict:
  # ukv:
  #   _target_: pvnet.models.multimodal.encoders.encoders3d.DefaultPVNet
  #   _partial_: True
  #   in_channels: 2
  #   out_features: 256
  #   number_of_conv3d_layers: 6
  #   conv3d_channels: 32
  #   image_size_pixels: 24
  # ecmwf:
  #   _target_: pvnet.models.multimodal.encoders.encoders3d.DefaultPVNet
  #   _partial_: True
  #   in_channels: 12
  #   out_features: 256
  #   number_of_conv3d_layers: 4
  #   conv3d_channels: 32
  #   image_size_pixels: 12
  gfs:
    # _target_: pvnet.models.multimodal.encoders.encoders3d.DefaultPVNet
    _target_: pvnet.models.multimodal.encoders.encoders3d.ResConv3DNet2
    _partial_: True
    in_channels: 14
    # out_features: 256
    out_features: 32
    # number_of_conv3d_layers:
    n_res_blocks: 1
    # conv3d_channels: 32
    hidden_channels: 6
    image_size_pixels: 2

#--------------------------------------------
# Sat encoder settings
#--------------------------------------------

# sat_encoder:
#   _target_: pvnet.models.multimodal.encoders.encoders3d.DefaultPVNet
#   _partial_: True
#   in_channels: 11
#   out_features: 256
#   number_of_conv3d_layers: 6
#   conv3d_channels: 32
#   image_size_pixels: 24

# add_image_embedding_channel: False

#--------------------------------------------
# PV encoder settings
#--------------------------------------------

# pv_encoder:
#   _target_: pvnet.models.multimodal.site_encoders.encoders.SingleAttentionNetwork
#   _partial_: True
#   num_sites: 349
#   out_features: 40
#   num_heads: 4
#   kdim: 40
#   id_embed_dim: 20

#--------------------------------------------
# Tabular network settings
#--------------------------------------------

output_network:
  _target_: pvnet.models.multimodal.linear_networks.networks.ResFCNet2
  _partial_: True
  fc_hidden_features: 128
  n_res_blocks: 6
  res_block_layers: 2
  dropout_frac: 0.0

embedding_dim: 16
include_sun: True
include_gsp_yield_history: False
include_site_yield_history: False

# The mapping between the location IDs and their embedding indices
# location_id_mapping:
#   1: 1
#   5: 2
#   110: 3
# ...

#--------------------------------------------
# Times
#--------------------------------------------

# Foreast and time settings
forecast_minutes: 480
history_minutes: 60

# min_sat_delay_minutes: 60

# These must also be set even if identical to forecast_minutes and  history_minutes
# sat_history_minutes: 90
# pv_history_minutes: 180

# These must be set for each NWP encoder
nwp_history_minutes:
  gfs: 180
  # ukv: 120
  # ecmwf: 120
nwp_forecast_minutes:
  gfs: 540
  # ukv: 480
  # ecmwf: 480
# Optional; defaults to 60, so must be set for data with different time resolution
nwp_interval_minutes:
  gfs: 180
  # ukv: 60
  # ecmwf: 60

# ----------------------------------------------
# Optimizer
# ----------------------------------------------
optimizer:
  _target_: pvnet.optimizers.EmbAdamWReduceLROnPlateau
  lr: 0.0001
  weight_decay: 0.01
  amsgrad: True
  patience: 5
  factor: 0.1
  threshold: 0.002
