_target_: pvnet.models.multimodal.multimodal.Model

optimizer:
  _target_: pvnet.optimizers.AdamW
  lr: 0.0001

output_network:
  _target_: pvnet.models.multimodal.linear_networks.networks.ResFCNet
  _partial_: true
  fc_hidden_features: 128
  n_res_blocks: 2
  res_block_layers: 2
  dropout_frac: 0.0

output_quantiles: [0.02, 0.1, 0.25, 0.5, 0.75, 0.9, 0.98]

nwp_encoders_dict:
  # ukv:
  #   _target_: pvnet.models.multimodal.encoders.encoders3d.ResConv3DNet
  #   _partial_: true
  #   in_channels: 1
  #   out_features: 256
  #   image_size_pixels: 24
  #   n_res_blocks: 4
  #   res_block_layers: 2
  #   dropout_frac: 0.0

add_image_embedding_channel: true
include_gsp_yield_history: false
include_sun: true
include_time: false
embedding_dim: 16
forecast_minutes: 480
history_minutes: 120
sat_history_minutes: 90
min_sat_delay_minutes: 30
nwp_forecast_minutes:
  ukv: 480
nwp_history_minutes:
  ukv: 120
sat_interval_minutes: 5
pv_interval_minutes: 5
nwp_interval_minutes:
  ukv: 60
