_target_: pvnet.data.DataModule
configuration: null

# The sample_dir is the location batches were saved to using the save_batches.py script
# The sample_dir should contain train and val subdirectories with batches

sample_dir: "GFS_samples"
num_workers: 8
prefetch_factor: 2
batch_size: 8
