_target_: pvnet.data.DataModule
# Path to the data configuration yaml file. You can find examples in the configuration subdirectory
# in configs.example/datamodule/configuration
# Use the full local path such as: /FULL/PATH/PVNet/configs/datamodule/configuration/gcp_configuration.yaml"
configuration: "/Users/jacquescamier/Development/ML_AI/open-data-pvnet/src/open_data_pvnet/configs/PVNet_configs/datamodule/configuration/example_configuration.yaml"
num_workers: 8
prefetch_factor: 2
batch_size: 8

sample_output_dir: "GFS_samples"
num_train_samples: 5 #1000 Increase at your discretion
num_val_samples: 5 #1000 Increase at your discretion

train_period:
  - null
  - "2023-06-30"
val_period:
  - "2023-07-01"
  - "2023-12-31"
